### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by basavind** [kursomir/kursomir.github.io#11]
Запилили первую версию [роадмапа](https://kursomir.github.io/roadmap), но она не информативна, поэтому предлагаю всем поучаствовать в решении проблемы полезности роадмапа как такового. Чтобы это все было читаемое и была видна однозначная последовательность действий в наших планах необходимо какой-то формат обговорить и утвердить.

Предлагаю такой вариант - весь роадмап должен быть плоским, т.е. представляться одним сплошным списком без вложений, в каждой задаче по роадмапу необходимо отразить вид действий необходимых для решения задачи (верстка, дизайн, фронтенд разработка и тд) и раздел, к чему относится задача. Раздел предлагаю просто помечать блоками кода, виды задач - emoji.

Например задача **дизайн админки новостей для проекта kursomir.ru** будет выглядеть следующим образом:

> 🎨  `kursomir.ru` админка новостей

Если есть другие предложения - прошу в комментарии. Если вариант с emoji все устраивает - предлагаю обговорить утвердить их список:

- [x] Дизайн 🎨
- [x] Проектирование 📝
- [x] Верстка 
- [x] Фронтенд разработка 
- [x] Бэкэнд разработка ⚙
- [x] Разработка мобильных приложений 📱
- [x] Администрирование, devops 📟

**Comment by ZverArt** [comment]
Согласен с предложением Димы. 
По поводу emoji:
Дизайн — окей. 
Проектирование — не очень понятно. Я бы использовал что-то типа 🚧 
Вёрстка — 🖥
Фронтэнд разработка — 🛠

Всё остальное в порядке вроде

**Comment by AgDust** [comment]
Emoji набирать не могу, поэтому согласен с любым вариантом :)

**Comment by basavind** [comment]
Здесь (в гитхабе) emoji можно набирать в текстовой форме - `:emoji_name:` (кстати достаточно двоеточие поставить и редактор сам предложит вставить эмоцию), например 😎 
Список emoji можно посмотреть [здесь](http://www.webpagefx.com/tools/emoji-cheat-sheet/)

**Comment by user1736** [comment]
Оно пока не сильно на roadmap похоже - нет никакой привязки ко времени и очередности в планах, может для начала в эту сторону посмотреть?

**Comment by basavind** [comment]
На родмап не похоже из-за групировки по направлениям, поэтому я и предлагаю избавиться от группировки, сделать все таски плоскими и поменять их очередность не в соответствии с группировкой, а в соответствии с их очередностью. Поэтому нам и нужна `хэш-функция` для перевода группировки в плоские таски :)

Ладно, сейчас тогда в пул-оформлю обновление, там обсудим.

**Comment by basavind** [comment]
* Перенести админку в `kursomir 2.1`
