### ISSUE TITLE
Иконки с языками/фреймворками для проектов

### ISSUE THREAD

**Issue by basavind** [kursomir/kursomir.github.io#6]
![proposal](https://cloud.githubusercontent.com/assets/1267239/23039114/8b2299ac-f49d-11e6-919b-83c09b088ba5.png)

**Comment by user1736** [comment]
@basavind, иконки мне самому искать? или я могу рассчитывать на готовую нарезку? :)

Так же вопрос о количестве иконок - у проекта может быть несколько технологий.

**Comment by basavind** [comment]
Насчет количества иконок - ну больше 3х их вряд ли будет :))
Про нарезку - иконки можно как всегда нагло стырить с одноименных сайтов :))

И забыл еще пометить - размер иконок 64х64

**Comment by user1736** [comment]
@basavind, ну если иконки искать мне, можешь тогда составить список на какой проект что лепить?
